name: build-main

on:
  push:
    branches:
      - main

jobs:
  build-main:

    runs-on: windows-2019
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: |
        pipenv install
    - name: Paint it black
      run: |
        pipenv run black_ci
    - name: Run tests
      run: |
        pipenv run test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
    - name: Read version number
      uses: pCYSl5EDgo/cat@master
      id: semver
      with:
        path: version.txt
    - name: Create FFI file
      run: |
        pipenv run create-version-file version.yml --outfile fixedfileinfo.txt --version ${{ steps.semver.outputs.text }}.${{ github.run_number }}
    - name: Build executable
      run: |
        pipenv run python -OO -m PyInstaller --clean --noconfirm --onefile --name wren --icon ./img/wren-logo-32.ico --version-file fixedfileinfo.txt ./wren/__main__.py
    - name: Create archive for release
      run: |
        7z a -tzip -bd wren.zip dist/wren.exe wren.cfg README.md
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: wren
        path: ${{ github.workspace }}/wren.zip
